
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-rec-s25-13
owner: ucsb-cs156-s25
repo_name: proj-rec-s25-13
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"tuan-student-removal","number":31,"title":"Tuan student removal","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/31"},{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"tuan-student-back-end-removal","number":27,"title":"Tuan student back end removal","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/27"},{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"tuan-student-front-end-removal","number":26,"title":"Removed student toggle from the front end","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/26"},{"author":{"id":"U_kgDOCM7m-A","is_bot":false,"login":"timothytwu","name":""},"headRefName":"timothy-admin-see-reqs","number":25,"title":"timothy - add admin requests page tests still pending","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/25"},{"author":{"id":"U_kgDOCM8Qxw","is_bot":false,"login":"k-nn-tht","name":"Kenneth Tan"},"headRefName":"kenneth-dev-bug-ensure_student_role","number":24,"title":"kenneth - changed default of student to true","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/24"}]
