
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-rec-s25-13
owner: ucsb-cs156-s25
repo_name: proj-rec-s25-13
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"tuan-nav-bar","number":53,"title":"Tuan - Nav Bar Permission Changes","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/53"},{"author":{"id":"MDQ6VXNlcjMwNDIwNTE0","is_bot":false,"login":"nikunjparasar","name":"Nikunj Parasar"},"headRefName":"np-fix-admin-bug","number":52,"title":"Nikunj - Fix Admin Page Self-Toggle Bug","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/52"},{"author":{"id":"MDQ6VXNlcjY1MDUwMDUz","is_bot":false,"login":"connersiou","name":""},"headRefName":"connersiou-professor-delete-endpoint","number":51,"title":"connersiou - added a delete endpoint for professor and changed some logic","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/51"},{"author":{"id":"MDQ6VXNlcjY1MDUwMDUz","is_bot":false,"login":"connersiou","name":""},"headRefName":"connersiou-modify-status-frontend","number":48,"title":"connersiou - prof can update status of requests in frontend","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/48"},{"author":{"id":"U_kgDOCI505Q","is_bot":false,"login":"chengcxi","name":""},"headRefName":"chengcxi-dev-RequestTypePages","number":46,"title":"Implemented Request Type Pages (create/post/delete).","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/46"}]
