
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-rec-s25-13
owner: ucsb-cs156-s25
repo_name: proj-rec-s25-13
pull_requests: [{"author":{"id":"U_kgDOCM8Qxw","is_bot":false,"login":"k-nn-tht","name":"Kenneth Tan"},"headRefName":"kenneth-feature-format_date","number":41,"title":"kenneth - changed the frontend for datetime values","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/41"},{"author":{"id":"U_kgDOCI505Q","is_bot":false,"login":"chengcxi","name":""},"headRefName":"chengcxi-dev-requestTypeTable","number":40,"title":"RequestTypeTable","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/40"},{"author":{"id":"MDQ6VXNlcjMwNDIwNTE0","is_bot":false,"login":"nikunjparasar","name":"Nikunj Parasar"},"headRefName":"np-student-profile-page","number":39,"title":"Nikunj - Table, Edit, and Form Integration for Student Profile Page","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/39"},{"author":{"id":"U_kgDOCM8Qxw","is_bot":false,"login":"k-nn-tht","name":"Kenneth Tan"},"headRefName":"kenneth-dev-subissue-test_coverage_usertables","number":38,"title":"kenneth - added coverage for usertable tests","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/38"},{"author":{"id":"U_kgDOCM7m-A","is_bot":false,"login":"timothytwu","name":""},"headRefName":"timothy-admin-req-page","number":37,"title":"Timothy - admin req page","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/37"},{"author":{"id":"U_kgDOCI505Q","is_bot":false,"login":"chengcxi","name":""},"headRefName":"chengcxi-dev","number":34,"title":"RequestTypeForm","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/34"}]
